"""CEO Briefing - Weekly autonomous business audit"""
import os
import json
from pathlib import Path
from datetime import datetime, timedelta
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def generate_ceo_briefing():
    """Generate Monday morning CEO briefing"""
    vault = Path(os.getenv('VAULT_PATH', './vault'))
    
    # Read source files
    goals = _read_markdown(vault / 'Business_Goals.md')
    current_month = _read_markdown(vault / 'Accounting/Current_Month.md')
    completed_tasks = _count_completed_tasks(vault / 'Done')
    transactions = _read_transactions(vault / 'Logs')
    
    # Calculate metrics
    revenue = _extract_revenue(current_month)
    completion_rate = _calculate_completion_rate(vault / 'Done', vault / 'Plans')
    bottlenecks = _identify_bottlenecks(vault / 'Logs')
    suggestions = _generate_suggestions(vault, transactions)
    
    # Generate briefing markdown
    briefing = f"""# Monday Morning CEO Briefing

**Period**: {(datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')} to {datetime.now().strftime('%Y-%m-%d')}
**Generated**: {datetime.now().isoformat()}

---

## Executive Summary
Weekly business performance review and autonomous audit results.

---

## Financial Summary

### Revenue
- **This Week**: ${revenue['weekly'] or 0:,.2f}
- **Month to Date**: ${revenue['monthly'] or 0:,.2f}
- **Monthly Target**: $10,000
- **Progress**: {int((revenue['monthly'] or 0) / 10000 * 100)}%

### Trend
{'✅ On track' if (revenue['monthly'] or 0) >= 2500 else '⚠️ Behind target'}

---

## Key Metrics

| Metric | Target | Actual | Status |
|--------|--------|--------|--------|
| Task Completion Rate | >85% | {completion_rate}% | {'✅' if completion_rate >= 85 else '⚠️'} |
| Response Time | <24h | Pending | ⏳ |
| Invoice Payment Rate | >90% | Pending | ⏳ |

---

## Completed Tasks This Week

{_generate_task_summary(vault / 'Done')}

---

## Bottlenecks Detected

{_format_bottlenecks(bottlenecks)}

---

## Proactive Suggestions

### Cost Optimization
{_format_suggestions(suggestions)}

### Upcoming Deadlines
- Q1 Tax Prep: Jan 31 (23 days)
- Q1 Review: Mar 31 (82 days)

---

## System Health

✅ Orchestrator: Running
✅ Watchers: Active
✅ Audit Logger: Recording
✅ Xero Integration: Ready

---

## Notes

- Review approval decisions in /Logs/
- Update Business_Goals.md as needed
- Adjust automation rules in Company_Handbook.md

---

*Generated by AI Employee Autonomous Audit*
*Next briefing: {(datetime.now() + timedelta(days=7)).strftime('%Y-%m-%d')}*
"""
    
    # Save briefing
    briefing_file = vault / 'Briefings' / f"{datetime.now().strftime('%Y-%m-%d')}_briefing.md"
    briefing_file.parent.mkdir(parents=True, exist_ok=True)
    briefing_file.write_text(briefing)
    
    logger.info(f"✅ Briefing generated: {briefing_file}")
    return briefing_file

def _read_markdown(path: Path) -> str:
    """Read markdown file"""
    return path.read_text() if path.exists() else ""

def _count_completed_tasks(done_dir: Path) -> int:
    """Count tasks in /Done/"""
    return len(list(done_dir.glob('*.md'))) if done_dir.exists() else 0

def _extract_revenue(month_md: str) -> dict:
    """Extract revenue numbers from Current_Month.md"""
    # Parse markdown table for income amounts
    weekly = 0.0
    monthly = 0.0
    
    if "**Month Total Income**" in month_md:
        try:
            line = [l for l in month_md.split('\n') if '**Month Total Income**' in l][0]
            monthly = float(''.join(c for c in line if c.isdigit() or c == '.'))
        except:
            pass
    
    return {'weekly': weekly, 'monthly': monthly}

def _calculate_completion_rate(done_dir: Path, plans_dir: Path) -> int:
    """Calculate task completion rate"""
    done_count = len(list(done_dir.glob('*.md'))) if done_dir.exists() else 0
    plans_count = len(list(plans_dir.glob('*.md'))) if plans_dir.exists() else 1
    return int((done_count / (done_count + plans_count)) * 100) if (done_count + plans_count) > 0 else 0

def _read_transactions(logs_dir: Path) -> list:
    """Read daily logs"""
    transactions = []
    if logs_dir.exists():
        for log_file in sorted(logs_dir.glob('*.json'), reverse=True)[:7]:
            try:
                with open(log_file) as f:
                    for line in f:
                        transactions.append(json.loads(line))
            except:
                pass
    return transactions

def _identify_bottlenecks(logs_dir: Path) -> list:
    """Identify tasks taking longer than expected"""
    # Would analyze execution times in logs
    return []

def _generate_suggestions(vault: Path, transactions: list) -> list:
    """Generate cost optimization suggestions"""
    suggestions = []
    # Analyze transaction patterns for unused subscriptions
    return suggestions or ["Review spending patterns", "Evaluate tool usage"]

def _generate_task_summary(done_dir: Path) -> str:
    """Generate summary of completed tasks"""
    tasks = list(done_dir.glob('*.md'))[:10] if done_dir.exists() else []
    if not tasks:
        return "- No tasks completed yet"
    return '\n'.join([f"- {t.stem}" for t in tasks])

def _format_bottlenecks(bottlenecks: list) -> str:
    """Format bottlenecks for display"""
    if not bottlenecks:
        return "✅ No bottlenecks detected this week"
    return '\n'.join([f"⚠️ {b}" for b in bottlenecks])

def _format_suggestions(suggestions: list) -> str:
    """Format suggestions for display"""
    return '\n'.join([f"- {s}" for s in suggestions]) if suggestions else "- All systems optimal"

if __name__ == '__main__':
    generate_ceo_briefing()
